version: "3"
services:
  node-app:
    build: .
    ports:
      - "4000:6000"
    environment:
      - PORT=6000
    
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ndungu
      - MONGO_INITDB_ROOT_PASSWORD=ndungu11
    volumes: 
      - mongodb:/data/db
    ports:
      - "6000:27017"


volumes:
  mongodb: