version: "3"
services:
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=ndungu
      - MONGO_PASSWORD=ndungu11
      #- MONGO_ip=172.24.0.3
    command: npm run dev

  # mongo:
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=ndungu
  #     - MONGO_INITDB_ROOT_PASSWORD=ndungu11