version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:6000"
    environment:
      - PORT=6000
    
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ndungu
      - MONGO_INITDB_ROOT_PASSWORD=ndungu11