version: "3"
services:
  node-app:
    build: .
    ports:
      - "4000:6000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - PORT=6000
    # env-file:
    #   - ./.env load environment variables in .env file